### ISSUE TITLE
hg19/ GRCh37 svg file missing

### ISSUE THREAD

**Issue by tpereachamblee** [alisi1989/RFmix2-Pipeline-to-plot#1]
Thank you for this wonderful and much needed toolkit for visualizing inferred local ancestry from rfmix v2 results!

I came across your preprint in bioarxiv and I decided to give the pipeline a try. It's very easy to use!

One issue that I notice is that for the local ancestry painting, `LAP.py` needs to find a file either named `hg38.svg` or `hg37.svg` and it looks like only the first of these two can be found here (specifying `-B hg37` fails). Is there a way to generate such a file or will the authors be able to include one in a future release?

Thanks again,
Tomin

**Comment by alisi1989** [comment]
Thank you for your interest in my pipeline. I'm pleased to inform you that we will soon be publishing an updated version of the software on GitHub. This new release will not only be simpler to use but will also include support for Build37.

I apologize for the delay in making this feature available. The process of constructing the chromosomes and determining their lengths took longer than anticipated.

Best regards,

Alessandro

**Comment by tpereachamblee** [comment]
No problem at all! Thank you so much, looking forward to the updated version of this software!

Best,
Tomin
